Update geo-types to 0.7.8
a-b-street/abstreet pull request #1032
Opened 2022-12-05 23:22 UTC by matthieu-foucault

On a new dev build, compiling fails due to the following error:

```
   Compiling geo-types v0.7.7
error: expected `,`, found `.`
   --> /home/matthieu/.cargo/registry/src/github.com-1ecc6299db9ec823/geo-types-0.7.7/src/geometry/geometry_collection.rs:111:25
    |
111 | #[deprecated(since = 0.7.5, note = "Use `GeometryCollection::from(vec![geom])` instead.")]
    |                         ^ expected `,`
```

This issue was [fixed in geo-types 0.7.8](https://github.com/georust/geo/commit/dbe5b4f1264fcf855e9c56096306e1bae65804aa), so I updated it using `cargo update --package geo-types`.

#

Side note: I am looking into contributing to this project over the next few weeks. I'll take a look at those [good first issues](https://github.com/a-b-street/abstreet/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) and see if I can open more PRs. Happy to hear any suggestions you might have re. where to start!

2022-12-05 23:32 UTC, dabreegster requested changes
Thank you for the fix! When I run `cargo check`, I get a handful of `use of deprecated type alias `geo::Coordinate`: Renamed to `geo_types::Coord` (or `geo::Coord`)` warnings. Would you mind fixing those up too?

I'll have a look through the good first issues tomorrow and make sure they're up-to-date. Any particular interest in a part of the project (like 15-minute neighbourhoods, or the traffic simulation) or a preference about the type of code (OpenStreetMap processing, more standard web dev, new features involving the UI code)?

2022-12-05 23:56 UTC, matthieu-foucault commented
> Would you mind fixing those up too?

Sure thing

#

> Any particular interest?

not really, the entire project looks interesting!

> a preference about the type of code 

I was looking for a cool open-source project to contribute to while improving my Rust skills. My expertise lies in web dev though, so I'd say mostly Rust interspersed with web dev things when I need to give my brain a break from learning a new language.

If you have any needs related to GitHub actions, I can definitely help with that. I'm thinking the issue solved here may have not been seen because the actions rely on a stale cache? Perhaps a nightly workflow that resets the cache would solve that?

Re. how much I'm looking to contribute, in case you're wondering: I'm currently an [Engineering Partner with Commit](https://commit.dev/for-engineers/), meaning that I have time to contribute to any project of my choosing to improve my skills, but I may be joining a startup anytime soon, so I don't know how long I'll be available to contribute.

2022-12-05 23:57 UTC, michaelkirk commented
What version of rust were you using when you hit that error? I'd only expect to see it affecting nightly at this point.

2022-12-06 00:11 UTC, matthieu-foucault commented
Ah, yes, I am using nightly


```
$ rustup show

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.67.0-nightly (b3bc6bf31 2022-11-24)
```

2022-12-06 00:19 UTC, matthieu-foucault commented
Should I open an issue/PR to add a [`toolchain.toml`](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) file?

2022-12-06 11:17 UTC, dabreegster commented
> Should I open an issue/PR to add a [toolchain.toml](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) file?

Not sure I've seen many projects specify `toolchain.toml` for stable, but it'd be fine to codify [the docs](https://a-b-street.github.io/docs/tech/dev/index.html) (which're outdated... latest stable, not 1.61)

> I'm thinking the issue solved here may have not been seen because the actions rely on a stale cache? Perhaps a nightly workflow that resets the cache would solve that?

No workflow builds everything on every commit right now. The project is small enough to make that unnecessary; there've never been more than a few people working on it at a time. There's a [release process](https://a-b-street.github.io/docs/tech/dev/release.html) that's a bit manual, but isn't worth automating further right now.

> not really, the entire project looks interesting!

A sampling of ideas, then... let me know if more context is useful for any of them

- The OSM processing code is now over in https://github.com/a-b-street/osm2streets, and there's a simple Leaflet viewer for it. https://github.com/a-b-street/osm2streets/issues/132#issuecomment-1339162927
- The LTN app draws road labels using https://github.com/a-b-street/abstreet/blob/ad99823cc886dfe5ccaea9581bb3e37d0a7ad6cf/map_gui/src/tools/labels.rs#L210. There are some cases when the label isn't centered vertically very well. And maybe you have design ideas to improve them generally?
- https://github.com/a-b-street/abstreet/issues/1013 New features for the bike network tool
- https://github.com/a-b-street/abstreet/issues/393 New features for 15-min neighbourhood tool, and also, plenty of directions this tool could go
- https://github.com/a-b-street/abstreet/issues/372 Very little public transit support today. It's a huge project, but there might be pieces to bite off that're fun
- https://github.com/a-b-street/abstreet/issues/88 If you have an eye for design
- https://github.com/a-b-street/abstreet/issues/85 Figuring out how to visualize changes in traffic volume, and more efficiently record them

2022-12-06 11:17 UTC, dabreegster approved these changes
Thanks for the build fix!

2022-12-06 11:18 UTC, merged