meter shows "finished trips vs baseline" instead of time
a-b-street/abstreet pull request #565
Opened 2021-03-15 23:36 UTC by michaelkirk

<img width="244" alt="Screen Shot 2021-03-15 at 4 34 47 PM" src="https://user-images.githubusercontent.com/217057/111234714-66c52f80-85ac-11eb-8dd9-71e7b97acdf3.png">

<img width="290" alt="Screen Shot 2021-03-15 at 4 34 54 PM" src="https://user-images.githubusercontent.com/217057/111234712-662c9900-85ac-11eb-9614-495ed42aa31c.png">

https://user-images.githubusercontent.com/217057/111234586-177eff00-85ac-11eb-9238-59c46fb11e4e.mp4

## edge cases

**next day**
<img width="260" alt="Screen Shot 2021-03-15 at 4 25 02 PM" src="https://user-images.githubusercontent.com/217057/111234591-1a79ef80-85ac-11eb-9cc5-ec8f1dd3234e.png">
**no prebaked day/night**
<img width="246" alt="Screen Shot 2021-03-15 at 4 24 24 PM" src="https://user-images.githubusercontent.com/217057/111234593-1a79ef80-85ac-11eb-87d2-df78b2a9b8e4.png">
<img width="251" alt="Screen Shot 2021-03-15 at 4 24 17 PM" src="https://user-images.githubusercontent.com/217057/111234594-1a79ef80-85ac-11eb-9a2c-ed55af3624c5.png">

**no changes**
<img width="270" alt="Screen Shot 2021-03-15 at 4 35 52 PM" src="https://user-images.githubusercontent.com/217057/111234765-852b2b00-85ac-11eb-995f-9be79ac0effe.png">

2021-03-15 23:51 UTC, dabreegster requested changes
Awesome job! I think this strikes a great balance between easy to learn the meaning of (with the tooltip) and succinct to glance at after knowing.

2021-03-15 23:51 UTC, dabreegster commented on game/src/sandbox/speed.rs
> +            for (t, _, _, _) in &app.prebaked().finished_trips[baseline_finished..] {
Ahhh, clever trick. Most of the things that read `Analytics` recalculate everything from scratch constantly. To one day speed this up, I was imagining making some kind of stateful "cursor" objects to remember where a computation left off. But that's total overkill for something like this -- just remembering the count is much simpler.

2021-03-15 23:51 UTC, dabreegster commented on game/src/sandbox/speed.rs
> +            Line(format!("Finished Trips: {}", prettyprint_usize(finished),)).fg(text_color),
nit: stray comma inside the format macro

2021-03-15 23:51 UTC, dabreegster commented on game/src/sandbox/speed.rs
> +            finished,
`prettyprint_usize(finished)`

2021-03-15 23:51 UTC, dabreegster commented on game/src/sandbox/speed.rs
> +                Line(format!("{} less than baseline", difference))
`prettyprint_usize` here and below, to help point out really dramatically high differences from the baseline

2021-03-16 00:07 UTC, michaelkirk commented
Ok, I believe I've responded to your feedback. PTAL @dabreegster

2021-03-16 00:10 UTC, dabreegster commented
Thanks for the PR!

2021-03-16 00:10 UTC, merged